project:
  type: website
  output-dir: docs
  resources:
    - CV_Hiroki_Chiba_HP.pdf

website:
  title: "Hiroki Chiba"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    toc: false
