project:
  type: website
  output-dir: docs
  resources:
    - CV_Hiroki_Chiba_HP.pdf

website:
  title: "Hiroki Chiba"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: miscellanea.qmd
        text: Miscellanea

format:
  html:
    theme: cosmo
    toc: false
